use_frameworks!

target 'CYUIViewTabbarButtons_Example' do
#  pod 'CYUIViewTabbarButtons', :path => '../'
pod 'CYUIViewTabbarButtons', :podspec => '../CYUIViewTabbarButtons.podspec'
target 'CYUIViewTabbarButtons_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
