use_frameworks!

target 'CYUIViewTabbarButtons_Example' do
  pod 'CYUIViewTabbarButtons', :path => '../'

  target 'CYUIViewTabbarButtons_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
